name: "devcontainer-with-dockercompose-test-compose-stack3"

services:
  app:
    image: "ruby:3.2.5"
    command: /bin/sh -c "tail -f /dev/null"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
